import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HomeComponent from "../components/HomeComponent";
import { PokemonType, PokemonList } from "../components/HomeComponent";
import { GetServerSideProps } from "next";

interface Props {
  pokemons: Array<PokemonType>;
}

const Home: NextPage<Props> = ({ pokemons }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeComponent pokemonList={pokemons} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const res = await fetch(
    "https://pokeapi.co/api/v2/pokemon/?offset=0&limit=20"
  );

  const json = await res.json();

  return { props: { pokemons: json.results } };
};

export default Home;
