export const pokemonActionTypes ={
    SET_TYPES : "SET_TYPES",
    SET_POKEMONS: "SET_POKEMONS",
    ADD_NEW_POKEMONS: "ADD_NEW_POKEMONS",
    SET_ACTIVE_TYPE:"SET_ACTIVE_TYPE",
    SET_ACTIVE_POKEMON:"SET_ACTIVE_POKEMON"
}